# Use a lightweight image with Python 3.11
FROM python:3.9

# Copy the rest of your app code
COPY . /app

WORKDIR /app/backend

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    tesseract-ocr

# Set environment variables
ENV TESSERACT_PATH=/usr/bin/tesseract
ENV PATH="${PATH}:/usr/bin"

RUN pip install --no-cache-dir -r requirements.txt

# Expose the port on which Uvicorn will run
EXPOSE 8000

# Command to run Uvicorn
CMD ["uvicorn", "main_gemini_collage:app", "--host", "0.0.0.0", "--port", "8000"]
